### ISSUE TITLE
Need print UTC timestamp for storage/os hang issue. 

### ISSUE THREAD

**Issue by xiangwu-ms** [koct9i/ioping#40]
if (!quiet) {
                        print_size(ret_size);
                        printf(" %s %s (%s %s", write_test ? ">>>" : "<<<",
                                        path, fstype, device);
                        if (device_size)
                                print_size(device_size);
                        time_t t = time(NULL);
                        struct tm tm = *gmtime(&t);
                        printf(": %d-%d-%d %d:%d:%d", tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday, tm.tm_hour, tm.tm_min, tm.tm_sec);
                        printf("): request=%lu time=", (long unsigned)request);
                        print_time(this_time);
                        if (request == 1) {
                                printf(" (warmup)");
                        } else if (this_time < min_valid_time) {
                                printf(" (too fast)");
                        } else if (this_time > max_valid_time) {
                                printf(" (too slow)");
                        } else if (part.valid > 5 && part.min < part.max) {
                                int percent = (this_time - part.min) * 100 /
                                                (part.max - part.min);
                                if (percent < 5)
                                        printf(" (fast)");
                                else if (percent > 95)
                                        printf(" (slow)");
                        }
                        printf("\n");
                }

**Comment by Tejeev** [comment]
What is it you are trying to do and what is it doing instead?  I'm trying to understand if your request is related to the one I was going to file but a codeblock without any info is only slightly helpful in understanding your issue.

**Comment by xiangwu-ms** [comment]
I am troubleshooting storage backend issue when customer reporting issues. The pain is I need exact UTC timestamp when there is high latency issue. Without the UTC timestamp, it makes me very difficult to troubleshoot.

**Comment by koct9i** [comment]
I've added realtime timestamps into json output format. Is this enough?

**Comment by Tejeev** [comment]
Not really, but it's ok.  Just using a different tool and a messy bash line.
JSON isn't so useful for me when trying to run quick things on customer clusters, since it then needs parsing.  Better to just ahve the option to output the timestamp in line:
$date 4096 bytes from . (ext4 /dev/sda3): request=1 time=0.2 ms

**Comment by koct9i** [comment]
You mean you need human readable date-time? It's easy to add into JSON.
I'll think about filtering normal requests so it will be silent until latency peak happens.

**Comment by Tejeev** [comment]
yes, as it is often run from cli by hand and because it's more universally parse-able by lnav and other log processing tools I use

**Comment by Tejeev** [comment]
filtering by peaks isn't good since what counts as a peak or out of bounds for an application depends on what is being run.  etcd has very different allowances from ceph, which going to be different from cockroachdb.  if I can just get good parse-able UTC timestamps that I don't have to write a JSON converter for in order to apply my normal workflows, ioping would be handy in a number of places.  JSON is great, if your tool understands it. Since we're in bash and cli on the front lines and often have to handle unique situations and investigate unique situations, it's more likely a tool can parse simple log formatted single line outputs, and if the tool doesn't do it, a bash one liner will.
